name: Run Newman Tests with NordLayer VPN (Testnet)

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: true

      - name: Update Last Processed Upstream Run ID
        run: |
          echo "${{ github.event.client_payload.run_id }}" > .last_upstream_run_id.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add .last_upstream_run_id.txt
          git commit -m "[skip ci] Update last processed upstream run id to ${{ github.event.client_payload.run_id }}" || echo "No changes to commit."
          git push

      - name: Install Dependencies (Newman, NordLayer, Datadog CLI)
        run: |
          npm install -g newman newman-reporter-htmlextra @datadog/datadog-ci

          echo "System Info:"
          lsb_release -a
          uname -m

          echo "Setting up NordLayer repository using local ./nordlayer/nordlayer-latest_1.0.0_all.deb..."
          if [ -f "./nordlayer/nordlayer-latest_1.0.0_all.deb" ]; then
            sudo dpkg -i ./nordlayer/nordlayer-latest_1.0.0_all.deb
          else
            echo "ERROR: Local repository setup file ./nordlayer/nordlayer-latest_1.0.0_all.deb not found!"
            exit 1
          fi
          
          sudo apt-get update -y
          sudo apt-get install -f -y
          
          echo "Installing NordLayer package..."
          sudo apt-get install -y nordlayer 

          echo "Reloading systemd daemon..."
          sudo systemctl daemon-reload
          
          echo "Attempting to stop NordLayer service (if running)..."
          sudo systemctl stop nordlayer.service || true

          echo "Attempting to enable and start NordLayer service..."
          if ! sudo systemctl enable --now nordlayer.service; then
            echo "ERROR: 'systemctl enable --now nordlayer.service' command failed."
            sudo systemctl status nordlayer.service --no-pager
            sudo journalctl -xeu nordlayer.service --no-pager -n 100
            exit 1
          fi
          echo "Command 'systemctl enable --now nordlayer.service' completed."

          echo "Waiting for NordLayer service to become fully active (max 60s)..."
          timeout 60s bash -c 'until systemctl is-active --quiet nordlayer.service; do echo "Waiting for nordlayer.service..."; sleep 3; done'
          
          if ! systemctl is-active --quiet nordlayer.service; then
            echo "ERROR: NordLayer service did not become active."
            sudo systemctl status nordlayer.service --no-pager
            sudo journalctl -xeu nordlayer.service --no-pager -n 100
            exit 1
          fi
          echo "NordLayer service IS reported ACTIVE by systemctl."
          
          SOCKET_PATH="/run/nordlayer/nordlayer.sock"
          echo "Checking for socket existence at $SOCKET_PATH immediately after service activation..."
          sleep 3 
          
          if [ -S "$SOCKET_PATH" ]; then
            echo "SUCCESS: Socket $SOCKET_PATH found."
            echo "Setting permissions on existing socket $SOCKET_PATH to 666 (rw-rw-rw-)..."
            sudo chmod 666 "$SOCKET_PATH"
            echo "Permissions on socket after chmod 666:"
            sudo ls -l "$SOCKET_PATH"
            # If needed, ensure parent directory is accessible enough for the 'runner' user to traverse.
            # Usually, runner doesn't need to list /run/nordlayer, just access the socket by its full path.
            # sudo chmod o+x /run/nordlayer # Example: allow others to execute (traverse) directory
          else
            echo "CRITICAL ERROR: Socket $SOCKET_PATH does NOT exist or is not a socket, even though service is active."
            echo "Listing /run/nordlayer/ directory contents:"
            sudo ls -la /run/nordlayer/ 
            echo "--- Status of nordlayer.service (when socket missing) ---"
            sudo systemctl status nordlayer.service --no-pager
            echo "--- Journal for nordlayer.service (last 100 lines, when socket missing) ---"
            sudo journalctl -xeu nordlayer.service --no-pager -n 100
            exit 1
          fi
          
          echo "End of Install Dependencies step. Pausing for 5s before login attempt..."
          sleep 5

      - name: Login to NordLayer VPN
        run: |
          SOCKET_PATH="/run/nordlayer/nordlayer.sock"
          echo "Login Step: Current user: $(whoami), Groups: $(groups)"
          echo "Login Step: Checking for socket $SOCKET_PATH existence *again* right before login..."
          
          if [ ! -S "$SOCKET_PATH" ]; then
            echo "CRITICAL ERROR (Login Step): Socket $SOCKET_PATH is MISSING or not a socket!"
            echo "Listing /run/nordlayer/ directory contents:"
            sudo ls -la /run/nordlayer/
            echo "--- Status of nordlayer.service (when socket missing at login) ---"
            sudo systemctl status nordlayer.service --no-pager
            echo "--- Journal for nordlayer.service (last 100 lines, when socket missing at login) ---"
            sudo journalctl -xeu nordlayer.service --no-pager -n 100
            exit 1
          else
            echo "Login Step: Socket $SOCKET_PATH FOUND. Proceeding with login."
            echo "Permissions of socket at login time:"
            sudo ls -l "$SOCKET_PATH"
          fi

          # Attempt login
          if ! nordlayer login --email "${{ secrets.NORDLAYER_EMAIL }}" --password "${{ secrets.NORDLAYER_PASSWORD }}" --organization "dydxopsdao"; then
            echo "ERROR: nordlayer login command failed."
            # This journal output is crucial if the error is 'connection reset' or similar,
            # less so if it's 'no such file or directory' as we've already covered that.
            echo "--- Journal for nordlayer.service (last 100 lines) AT TIME OF LOGIN FAILURE ---"
            sudo journalctl -xeu nordlayer.service --no-pager -n 100 
            exit 1
          fi
          echo "NordLayer login successful."

      # ... (Rest of the workflow: Connect, Newman, Disconnect, Uploads, Slack - remains the same) ...
      - name: Connect to NordLayer VPN
        run: |
          nordlayer gateways
          nordlayer connect "dos-server-BQG2cKQV"
          sleep 20 
          echo "Verifying VPN IP..."
          curl --max-time 10 ifconfig.me || echo "Warning: Could not verify external IP."

      - name: Run Newman Tests for Testnet
        id: newman
        run: |
          newman run postman/collection.json \
            -e postman/environment.testnet.json \
            --reporters cli,htmlextra,junit \
            --reporter-htmlextra-export newman-report.html \
            --reporter-junit-export results.xml
          NEWMAN_EXIT_CODE=$?
          echo "exit_code=${NEWMAN_EXIT_CODE}" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Disconnect from NordLayer VPN
        if: always()
        run: |
          nordlayer status || true
          nordlayer disconnect || echo "Already disconnected or failed to disconnect."

      - name: Upload Test Results (JUnit XML)
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: postman-test-results
          path: results.xml
          if-no-files-found: warn

      - name: Upload HTML Report (Nice UI)
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: postman-html-report
          path: newman-report.html
          if-no-files-found: warn

      - name: Notify Slack Channel and Handle Failure
        if: always()
        run: |
          NEWMAN_EXIT_CODE="${{ steps.newman.outputs.exit_code }}" 
          JOB_STATUS="${{ job.status }}"
          FINAL_MESSAGE=""
          ICON=":test_tube:" 
          COLOR="warning" 
          TITLE_TEXT="NordLayer & Newman Test Run (Testnet on ubuntu-22.04)"

          if [ "$JOB_STATUS" == "success" ]; then
            if [ -z "$NEWMAN_EXIT_CODE" ] || [ "$NEWMAN_EXIT_CODE" -eq 0 ]; then
              FINAL_MESSAGE="All tests passed successfully!"
              ICON=":white_check_mark:"
              COLOR="good"
            else
              FINAL_MESSAGE="Newman tests completed but encountered failures (Exit Code: $NEWMAN_EXIT_CODE)."
              ICON=":warning:"
              COLOR="danger" 
            fi
          else 
            FINAL_MESSAGE="Workflow step failed prior to or during Newman tests. Check Actions run."
            ICON=":x:"
            COLOR="danger"
          fi
          
          TEXT_MESSAGE="$FINAL_MESSAGE Workflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} Run #${{ github.run_number }}>"
          PAYLOAD=$(jq -n \
            --arg channel "indexer-api-testing" \
            --arg username "GitHub Actions" \
            --arg icon_emoji "$ICON" \
            --arg color "$COLOR" \
            --arg title "$TITLE_TEXT" \
            --arg text "$TEXT_MESSAGE" \
            '{channel: $channel, username: $username, icon_emoji: $icon_emoji, attachments: [{color: $color, title: $title, text: $text}]}')
          
          echo "$PAYLOAD"
          curl -X POST -H "Content-type: application/json" --data "$PAYLOAD" "${{ secrets.SLACK_WEBHOOK_URL }}"

          if [ "$JOB_STATUS" == "failure" ]; then
            exit 1
          elif [ -n "$NEWMAN_EXIT_CODE" ] && [ "$NEWMAN_EXIT_CODE" -ne 0 ]; then
            exit 1
          fi
